"""orgs_act_names_unique

Revision ID: 01c07461a992
Revises: 2ccdd25fb04b
Create Date: 2026-01-16 12:57:16.960691

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '01c07461a992'
down_revision: Union[str, None] = '2ccdd25fb04b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'activities', ['name'])
    op.create_unique_constraint(None, 'organizations', ['name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'organizations', type_='unique')
    op.drop_constraint(None, 'activities', type_='unique')
    # ### end Alembic commands ###
