"""Activity

Revision ID: 1bb7355d7193
Revises: a0614cbcee4f
Create Date: 2026-01-15 21:37:49.502014

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1bb7355d7193'
down_revision: Union[str, None] = 'a0614cbcee4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('activities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['parent_id'], ['activities.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('parent_id', 'name', name='uq_activity_parent_name')
    )
    op.create_index(op.f('ix_activities_parent_id'), 'activities', ['parent_id'], unique=False)
    op.create_index('ix_activity_parent_name', 'activities', ['parent_id', 'name'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_activity_parent_name', table_name='activities')
    op.drop_index(op.f('ix_activities_parent_id'), table_name='activities')
    op.drop_table('activities')
    # ### end Alembic commands ###
