"""organizations-2

Revision ID: 2ccdd25fb04b
Revises: c8b3cfdd5139
Create Date: 2026-01-15 21:49:12.169627

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2ccdd25fb04b'
down_revision: Union[str, None] = 'c8b3cfdd5139'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
