"""init

Revision ID: 347df5c9fe37
Revises: 
Create Date: 2026-01-15 19:53:00.309776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '347df5c9fe37'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('addresses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('country', sa.Text(), nullable=False),
    sa.Column('city', sa.Text(), nullable=False),
    sa.Column('street', sa.Text(), nullable=False),
    sa.Column('house', sa.Integer(), nullable=False),
    sa.Column('building', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('country', 'city', 'street', 'house', 'building', name='uq_addresses_full')
    )
    op.create_index('ix_addresses_lookup', 'addresses', ['country', 'city', 'street', 'house'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_addresses_lookup', table_name='addresses')
    op.drop_table('addresses')
    # ### end Alembic commands ###
