"""addres_coordinates

Revision ID: a0614cbcee4f
Revises: 347df5c9fe37
Create Date: 2026-01-15 19:59:50.434678

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0614cbcee4f'
down_revision: Union[str, None] = '347df5c9fe37'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('addresses', sa.Column('lat', sa.Float(), nullable=True))
    op.add_column('addresses', sa.Column('lon', sa.Float(), nullable=True))
    op.create_index('ix_addresses_geo', 'addresses', ['lat', 'lon'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_addresses_geo', table_name='addresses')
    op.drop_column('addresses', 'lon')
    op.drop_column('addresses', 'lat')
    # ### end Alembic commands ###
