"""organization

Revision ID: c8b3cfdd5139
Revises: 1bb7355d7193
Create Date: 2026-01-15 21:45:16.744148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c8b3cfdd5139'
down_revision: Union[str, None] = '1bb7355d7193'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('organizations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('address_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['address_id'], ['addresses.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_org_name', 'organizations', ['name'], unique=False)
    op.create_index(op.f('ix_organizations_address_id'), 'organizations', ['address_id'], unique=False)
    op.create_table('organization_activities',
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('activity_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['activity_id'], ['activities.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('organization_id', 'activity_id')
    )
    op.create_index('ix_org_act_activity', 'organization_activities', ['activity_id'], unique=False)
    op.create_table('organization_phones',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('organization_id', sa.Integer(), nullable=False),
    sa.Column('phone', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('organization_id', 'phone', name='uq_org_phone')
    )
    op.create_index('ix_org_phone_phone', 'organization_phones', ['phone'], unique=False)
    op.create_index(op.f('ix_organization_phones_organization_id'), 'organization_phones', ['organization_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_organization_phones_organization_id'), table_name='organization_phones')
    op.drop_index('ix_org_phone_phone', table_name='organization_phones')
    op.drop_table('organization_phones')
    op.drop_index('ix_org_act_activity', table_name='organization_activities')
    op.drop_table('organization_activities')
    op.drop_index(op.f('ix_organizations_address_id'), table_name='organizations')
    op.drop_index('ix_org_name', table_name='organizations')
    op.drop_table('organizations')
    # ### end Alembic commands ###
